/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Entity4, Entity4Create } from './dtos/Entity4.dto';
import { Entity4Controller } from './Entity4.controller';
import { Entity4Service } from './Entity4.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('Entity4Controller', () => {
  let controller: Entity4Controller;
  let spyService: Entity4Service;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: Entity4Service,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [Entity4Controller],
      providers: [Entity4Service, ApiServiceProvider],
    }).compile();

    controller = module.get<Entity4Controller>(Entity4Controller);
    spyService = module.get<Entity4Service>(Entity4Service);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call Entity4Controller get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call Entity4Controller create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Entity4();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
