/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Entity4 } from './Entity4.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Entity4Service } from './Entity4.service';
import { Entity4Controller } from './Entity4.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Entity4])],
  providers: [Entity4Service],
  exports: [Entity4Service],
  controllers: [Entity4Controller],
})
export class Entity4Module {}
