/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Entity2 } from './Entity2.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Entity2Service } from './Entity2.service';
import { Entity2Controller } from './Entity2.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Entity2])],
  providers: [Entity2Service],
  exports: [Entity2Service],
  controllers: [Entity2Controller],
})
export class Entity2Module {}
