/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Entity2, Entity2Create } from './dtos/Entity2.dto';
import { Entity2Controller } from './Entity2.controller';
import { Entity2Service } from './Entity2.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('Entity2Controller', () => {
  let controller: Entity2Controller;
  let spyService: Entity2Service;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: Entity2Service,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [Entity2Controller],
      providers: [Entity2Service, ApiServiceProvider],
    }).compile();

    controller = module.get<Entity2Controller>(Entity2Controller);
    spyService = module.get<Entity2Service>(Entity2Service);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call Entity2Controller get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call Entity2Controller create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Entity2();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
