/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Entity9, Entity9Create } from './dtos/Entity9.dto';
import { Entity9Controller } from './Entity9.controller';
import { Entity9Service } from './Entity9.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('Entity9Controller', () => {
  let controller: Entity9Controller;
  let spyService: Entity9Service;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: Entity9Service,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [Entity9Controller],
      providers: [Entity9Service, ApiServiceProvider],
    }).compile();

    controller = module.get<Entity9Controller>(Entity9Controller);
    spyService = module.get<Entity9Service>(Entity9Service);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call Entity9Controller get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call Entity9Controller create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Entity9();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
