/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Entity9 } from './Entity9.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Entity9Service } from './Entity9.service';
import { Entity9Controller } from './Entity9.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Entity9])],
  providers: [Entity9Service],
  exports: [Entity9Service],
  controllers: [Entity9Controller],
})
export class Entity9Module {}
