import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class Entity8Create {
  @ApiProperty()
  field1: string;
  @ApiProperty()
  field2: string;
  @ApiProperty()
  field3: string;
  @ApiProperty()
  field4: string;
  @ApiProperty()
  field5: string;
}

export class Entity8 {
  @ApiProperty()
  id: number;
  @ApiProperty()
  field1: string;
  @ApiProperty()
  field2: string;
  @ApiProperty()
  field3: string;
  @ApiProperty()
  field4: string;
  @ApiProperty()
  field5: string;
}
