/**
 * This file generated by Apso.
 */
import { Entity1Module } from './Entity1/Entity1.module';
import { Entity2Module } from './Entity2/Entity2.module';
import { Entity3Module } from './Entity3/Entity3.module';
import { Entity4Module } from './Entity4/Entity4.module';
import { Entity5Module } from './Entity5/Entity5.module';
import { Entity6Module } from './Entity6/Entity6.module';
import { Entity7Module } from './Entity7/Entity7.module';
import { Entity8Module } from './Entity8/Entity8.module';
import { Entity9Module } from './Entity9/Entity9.module';
import { Entity10Module } from './Entity10/Entity10.module';

export default [
  Entity1Module,
  Entity2Module,
  Entity3Module,
  Entity4Module,
  Entity5Module,
  Entity6Module,
  Entity7Module,
  Entity8Module,
  Entity9Module,
  Entity10Module,
];
