/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Entity5 } from './Entity5.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Entity5Service } from './Entity5.service';
import { Entity5Controller } from './Entity5.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Entity5])],
  providers: [Entity5Service],
  exports: [Entity5Service],
  controllers: [Entity5Controller],
})
export class Entity5Module {}
