/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Entity10, Entity10Create } from './dtos/Entity10.dto';
import { Entity10Controller } from './Entity10.controller';
import { Entity10Service } from './Entity10.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('Entity10Controller', () => {
  let controller: Entity10Controller;
  let spyService: Entity10Service;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: Entity10Service,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [Entity10Controller],
      providers: [Entity10Service, ApiServiceProvider],
    }).compile();

    controller = module.get<Entity10Controller>(Entity10Controller);
    spyService = module.get<Entity10Service>(Entity10Service);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call Entity10Controller get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call Entity10Controller create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Entity10();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
