/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Entity10 } from './Entity10.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Entity10Service } from './Entity10.service';
import { Entity10Controller } from './Entity10.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Entity10])],
  providers: [Entity10Service],
  exports: [Entity10Service],
  controllers: [Entity10Controller],
})
export class Entity10Module {}
