/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Entity8 } from './Entity8.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Entity8Service } from './Entity8.service';
import { Entity8Controller } from './Entity8.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Entity8])],
  providers: [Entity8Service],
  exports: [Entity8Service],
  controllers: [Entity8Controller],
})
export class Entity8Module {}
