/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Entity8, Entity8Create } from './dtos/Entity8.dto';
import { Entity8Controller } from './Entity8.controller';
import { Entity8Service } from './Entity8.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('Entity8Controller', () => {
  let controller: Entity8Controller;
  let spyService: Entity8Service;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: Entity8Service,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [Entity8Controller],
      providers: [Entity8Service, ApiServiceProvider],
    }).compile();

    controller = module.get<Entity8Controller>(Entity8Controller);
    spyService = module.get<Entity8Service>(Entity8Service);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call Entity8Controller get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call Entity8Controller create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Entity8();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
