/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Entity3 } from './Entity3.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Entity3Service } from './Entity3.service';
import { Entity3Controller } from './Entity3.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Entity3])],
  providers: [Entity3Service],
  exports: [Entity3Service],
  controllers: [Entity3Controller],
})
export class Entity3Module {}
