/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Entity3, Entity3Create } from './dtos/Entity3.dto';
import { Entity3Controller } from './Entity3.controller';
import { Entity3Service } from './Entity3.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('Entity3Controller', () => {
  let controller: Entity3Controller;
  let spyService: Entity3Service;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: Entity3Service,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [Entity3Controller],
      providers: [Entity3Service, ApiServiceProvider],
    }).compile();

    controller = module.get<Entity3Controller>(Entity3Controller);
    spyService = module.get<Entity3Service>(Entity3Service);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call Entity3Controller get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call Entity3Controller create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Entity3();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
