/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Entity1 } from './Entity1.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Entity1Service } from './Entity1.service';
import { Entity1Controller } from './Entity1.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Entity1])],
  providers: [Entity1Service],
  exports: [Entity1Service],
  controllers: [Entity1Controller],
})
export class Entity1Module {}
