/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Entity1, Entity1Create } from './dtos/Entity1.dto';
import { Entity1Controller } from './Entity1.controller';
import { Entity1Service } from './Entity1.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('Entity1Controller', () => {
  let controller: Entity1Controller;
  let spyService: Entity1Service;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: Entity1Service,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [Entity1Controller],
      providers: [Entity1Service, ApiServiceProvider],
    }).compile();

    controller = module.get<Entity1Controller>(Entity1Controller);
    spyService = module.get<Entity1Service>(Entity1Service);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call Entity1Controller get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call Entity1Controller create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Entity1();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
