/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Entity7 } from './Entity7.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Entity7Service } from './Entity7.service';
import { Entity7Controller } from './Entity7.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Entity7])],
  providers: [Entity7Service],
  exports: [Entity7Service],
  controllers: [Entity7Controller],
})
export class Entity7Module {}
