/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Entity7, Entity7Create } from './dtos/Entity7.dto';
import { Entity7Controller } from './Entity7.controller';
import { Entity7Service } from './Entity7.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('Entity7Controller', () => {
  let controller: Entity7Controller;
  let spyService: Entity7Service;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: Entity7Service,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [Entity7Controller],
      providers: [Entity7Service, ApiServiceProvider],
    }).compile();

    controller = module.get<Entity7Controller>(Entity7Controller);
    spyService = module.get<Entity7Service>(Entity7Service);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call Entity7Controller get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call Entity7Controller create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Entity7();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
