/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Entity6, Entity6Create } from './dtos/Entity6.dto';
import { Entity6Controller } from './Entity6.controller';
import { Entity6Service } from './Entity6.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('Entity6Controller', () => {
  let controller: Entity6Controller;
  let spyService: Entity6Service;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: Entity6Service,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [Entity6Controller],
      providers: [Entity6Service, ApiServiceProvider],
    }).compile();

    controller = module.get<Entity6Controller>(Entity6Controller);
    spyService = module.get<Entity6Service>(Entity6Service);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call Entity6Controller get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call Entity6Controller create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Entity6();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
