/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Entity6 } from './Entity6.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Entity6Service } from './Entity6.service';
import { Entity6Controller } from './Entity6.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Entity6])],
  providers: [Entity6Service],
  exports: [Entity6Service],
  controllers: [Entity6Controller],
})
export class Entity6Module {}
